=== abdelhalimess/Semi-Structured-Data-XML-Xquery/trip_hautes_alpes1.dtd
<!ELEMENT TravelData (Guide,Location,Itinerary)>
<!ELEMENT Guide (#PCDATA)>
<!ELEMENT Location (ValleeDeLaClaree,VallonDesMuandes)>
<!ELEMENT ValleeDeLaClaree (Description)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT VallonDesMuandes (Description)>
<!ELEMENT Itinerary (Route+)>
<!ELEMENT Route (Name,Description,Elevation)>
<!ATTLIST Route number NMTOKEN #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Elevation (#PCDATA)>

=== abdelhalimess/Semi-Structured-Data-XML-Xquery/trip_hautes_alpes.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE TravelData SYSTEM "trip_hautes_alpes1.dtd">
<TravelData>
  <Guide>Jean-Gabriel Ravary</Guide>
  <Location>
    <ValleeDeLaClaree>
      <Description>Situated north of Briançon in the Hautes-Alpes department.</Description>
    </ValleeDeLaClaree>
    <VallonDesMuandes>
      <Description>Vallon located to the east of the Drayères refuge. The most commonly used valley for crossing to the Vallée Etroite. This valley is also accessible from the Laval refuge.</Description>
    </VallonDesMuandes>
  </Location>
  <Itinerary>
    <Route number="1">
      <Name>Col de Névache</Name>
      <Description>S'élever au-dessus du refuge des Drayères en direction est. Suivre la rive droite du torrent de Brune puis s’engager sur le flanc droit du ravin des Muandes que l’on quitte vers 2500 m pour rejoindre le col situé au nord. Descente possible sur Valmeinier. Départ assez raide.</Description>
      <Elevation>2 794 m</Elevation>
    </Route>
    <Route number="2">
      <Name>Pointe de Névache</Name>
      <Description>Du col de Névache (itinéraire n° 1), suivre la ligne de crête qui mène à la pointe de Névache. Attention : corniches possibles. Crampons utiles au printemps.</Description>
      <Elevation>2 892 m</Elevation>
    </Route>
  </Itinerary>
</TravelData>
